#!/bin/sh

echo "*** Git hook start"
echo

echo "*** Formatting source files with clang-format..."
find src -type f \( -name "*.cpp" -o -name "*.hpp" \) -print0 |
  xargs -0 clang-format -style=file -i -fallback-style=none

echo
echo "*** Git hook done"
