#!/bin/sh

SCRIPT_DIR=$(cd -- "$(dirname -- "$0")" && pwd)

echo "*** Git hook start"
echo

echo "*** Formatting source files with clang-format..."
"$SCRIPT_DIR/../utils/docker-clang-format.sh"

echo
echo "*** Git hook done"
